changelog:
  exclude:
    labels:
      - ignore-for-release
      - wip
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - new
    - title: Other Changes
      labels:
        - "*"