
typedef enum {
    EVENT_SW_CLICK,
    EVENT_PRINTER_IDLE,
    EVENT_PREHEAT_BED,
    EVENT_CLEANING_NOZZLE,
    EVENT_BED_LEVELING,
    EVENT_EXTRUSION_CALIBRATION,
    EVENT_PRINTING,
    EVENT_PRINT_FINISHED,
    EVENT_PRINT_FAILED,
    EVENT_DOOR_OPEN_IDLE,
    EVENT_DOOR_CLOSE_IDLE,
    EVENT_DOOR_OPEN_PRINT,
    EVENT_DOOR_CLOSE_PRINT,
    EVENT_DOOR_OPEN_FINISH,
    EVENT_DOOR_CLOSE_FINISH
} EventType;


void eventBus(EventType event) {
}